# Generated by Django 5.2.14 on 2026-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="commission_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="commission_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
