# Generated by Django 4.2.11 on 2026-05-08 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_product_name_trgm_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=500
                    ),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "seo_configs",
            },
        ),
    ]
