# Generated by Django 4.2.11 on 2026-05-08 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="buyer",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "buyer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
