# Generated by Django 4.2.11 on 2026-05-08 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0005_order_carrier_order_shipping_rate_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_number", models.CharField(max_length=255, unique=True)),
                ("carrier", models.CharField(max_length=100)),
                ("status", models.CharField(default="label_created", max_length=50)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "shipment_trackers",
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipmenttracker",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
