# Generated by Django 5.2.14 on 2026-05-08 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_clicks_count_product_views_count_collection"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_pricing",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "promo_pricing",
                "ordering": ["-start_date"],
            },
        ),
    ]
