# Generated by Django 4.2.11 on 2026-05-08 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0006_product_product_name_trgm_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_sellers", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "top_selling_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "daily_metrics",
                "ordering": ["-date"],
            },
        ),
    ]
